//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pract18
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        public string Name_of_the_medicine { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> Number_of_units { get; set; }
        public Nullable<System.DateTime> Product_date { get; set; }
        public Nullable<System.DateTime> Expiration_date { get; set; }
        public string Factory_name { get; set; }
        public string Factory_address { get; set; }
    }
}
