USE [master]
GO

/****** Object:  Database [Accounting of medicines]    Script Date: 30.03.2023 10:05:37 ******/
CREATE DATABASE [Accounting of medicines]
 
ALTER DATABASE [Accounting of medicines] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Accounting of medicines] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Accounting of medicines] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Accounting of medicines] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Accounting of medicines] SET ARITHABORT OFF 
GO

ALTER DATABASE [Accounting of medicines] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Accounting of medicines] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Accounting of medicines] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Accounting of medicines] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Accounting of medicines] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Accounting of medicines] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Accounting of medicines] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Accounting of medicines] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Accounting of medicines] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Accounting of medicines] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Accounting of medicines] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Accounting of medicines] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Accounting of medicines] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Accounting of medicines] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Accounting of medicines] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Accounting of medicines] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Accounting of medicines] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Accounting of medicines] SET RECOVERY FULL 
GO

ALTER DATABASE [Accounting of medicines] SET  MULTI_USER 
GO

ALTER DATABASE [Accounting of medicines] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Accounting of medicines] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Accounting of medicines] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Accounting of medicines] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Accounting of medicines] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Accounting of medicines] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Accounting of medicines] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Accounting of medicines] SET  READ_WRITE 
GO


